server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/PocketPal
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
jwt:
  # CHANGE THIS IN YOUR OWN APPLICATION!!!
  secret: 546A576E5A7234753778214125442A472D4B6150645367566B58703273357638
